### ISSUE TITLE
Large gml file conversion to Cityjson

### ISSUE THREAD

**Issue by Saji70** [citygml4j/citygml-tools#23]
Dear Citygml team

I want to convert large CityGML file (~4GB) to CityJson but I encontered following Error: any advice to resolve it?
##
[19:49:35 ERROR] The following unexpected error occurred during execution.
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at com.sun.xml.bind.DatatypeConverterImpl._parseDouble(DatatypeConverterImpl.java:207)
        at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$21.parse(RuntimeBuiltinLeafInfoImpl.java:749)
        at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$21.parse(RuntimeBuiltinLeafInfoImpl.java:747)
        at com.sun.xml.bind.v2.runtime.reflect.ListTransducedAccessorImpl.processValue(ListTransducedAccessorImpl.java:110)
        at com.sun.xml.bind.v2.runtime.reflect.ListTransducedAccessorImpl.parse(ListTransducedAccessorImpl.java:125)
        at com.sun.xml.bind.v2.runtime.unmarshaller.ValuePropertyLoader.text(ValuePropertyLoader.java:37)
        at com.sun.xml.bind.v2.runtime.unmarshaller.StructureLoader.text(StructureLoader.java:261)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.text(UnmarshallingContext.java:560)
        at com.sun.xml.bind.v2.runtime.unmarshaller.InterningXmlVisitor.text(InterningXmlVisitor.java:63)
        at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.processText(StAXStreamConnector.java:308)
        at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.handleEndElement(StAXStreamConnector.java:186)
        at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:155)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:385)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:356)
        at org.citygml4j.builder.jaxb.xml.io.reader.JAXBSimpleReader.nextFeature(JAXBSimpleReader.java:133)
        at org.citygml4j.tools.command.ToCityJSONCommand.call(ToCityJSONCommand.java:107)
        at org.citygml4j.tools.command.ToCityJSONCommand.call(ToCityJSONCommand.java:50)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2422)
        at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2424)
        at picocli.CommandLine$RunAll.handle(CommandLine.java:2419)
        at picocli.CommandLine$RunAll.handle(CommandLine.java:2383)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at org.citygml4j.tools.CityGMLTools.process(CityGMLTools.java:131)
        at org.citygml4j.tools.CityGMLTools.main(CityGMLTools.java:87)
[19:49:35 WARN] citygml-tools execution failed.
##
Thanks

**Comment by clausnagel** [comment]
Closing due to lack of feedback. Feel free to re-open.
